Api/add expense
detectiveno2/expense-management-api pull request #24
Opened 2020-09-01 02:49 UTC by nguynhieu

2020-09-01 04:32 UTC, detectiveno2 reviewed
vai, hinh nhu mình làm như ri là hắn chỉ thêm trong ngày thôi á cu Hiếu, hok thêm trong quá khứ được, bên client của mình có chọn ngày á

2020-09-01 04:32 UTC, detectiveno2 commented on api/controllers/expense.controller.js
> +	const { expense, isIncome, title, description, walletName } = req.body;
khúc ni mình cần cái date nè cu Hiếu, date để lỡ mà user thêm 1 giao dịch ở những ngày trong quá khứ á, chớ hok phải họ luôn luôn thêm giao dịch ngay trong ngày nớ ák

2020-09-01 08:52 UTC, detectiveno2 requested changes
anh thấy có 3 chỗ mình cần sửa á, cu Hiếu xem thử nka

2020-09-01 08:52 UTC, detectiveno2 commented on api/controllers/expense.controller.js
> +	return res.json(newData);
khúc ni mình thiếu status nè, trong trường hợp ni anh nghĩ CREATED_STATUS là hợp lý đó

2020-09-01 08:52 UTC, detectiveno2 commented on api/controllers/expense.controller.js
> +						expense,
expense chỗ ni mình xét âm dương nữa nè cu Hiếu

2020-09-01 08:52 UTC, detectiveno2 commented on api/controllers/expense.controller.js
> +
Anh quên mất, lúc mình set vào á, là mình cần update cho trường accountBalance nữa, là trường tính tiền hiện tại á

2020-09-01 20:52 UTC, detectiveno2 requested changes

2020-09-01 20:52 UTC, detectiveno2 commented on api/controllers/expense.controller.js
> +	const newExpense = (isIncome && expense) || -expense;
```suggestion
	const newExpense = isIncome ? expense : -expense;
```
cu Hiếu thử cái ni thử, anh thử thấy được, như cái cũ là isIncome true hay false chi hắn cũng dương hết

2020-09-01 20:53 UTC, detectiveno2 commented on api/controllers/expense.controller.js
> +	const newExpense = (isIncome && expense) || -expense;
xong cái âm dương ni là anh merge vô luôn ák

2020-09-02 00:08 UTC, nguynhieu commented on api/controllers/expense.controller.js
> +	const newExpense = (isIncome && expense) || -expense;
ua ben a duoc ma daika

2020-09-02 00:22 UTC, merged